# Generated by Django 3.0 on 2021-11-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20211122_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='type_food',
            field=models.CharField(choices=[('B', 'صبحانه'), ('DR', 'نوشیدنی'), ('L', 'ناهار'), ('D', 'شام')], default='DR', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
