# Generated by Django 3.0 on 2021-11-30 22:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_foods_type_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foods',
            name='description',
            field=models.CharField(max_length=300, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='foods.Foods')),
            ],
        ),
    ]
