# Generated by Django 3.0 on 2021-11-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20211201_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=25)),
                ('l_name', models.CharField(max_length=25)),
                ('numbers', models.IntegerField()),
                ('email', models.EmailField(default='ali@gmail.com', max_length=250, unique=True)),
                ('address', models.TextField()),
                ('post_num', models.IntegerField()),
                ('receiver_name', models.CharField(max_length=20)),
            ],
        ),
    ]
